### ISSUE TITLE
binary package doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by tetron** [rabix/benten#110]
The binary package is mostly self-contained but it still relies on glibc:

> Error loading Python lib '/home/sarah/.local/share/sevenbridges/benten/benten-2021.1.5/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/sarah/.local/share/sevenbridges/benten/benten-2021.1.5/libpython3.8.so.1.0)

I think the problem is we build with `ubuntu-latest` which is 18.04.  According to https://github.com/actions/virtual-environments `ubuntu-16.04` is also available so we should see how hard it would be to build on that instead.

I'm also wondering now if this package is going to work on centos7.

**Comment by tetron** [comment]
ubuntu 16.04 seems to have glibc 2.23

centos7 seems to have glibc 2.17

So for maximum compatibility it would be good if we could build the linux package on centos7 somehow.

**Comment by tetron** [comment]
github actions doesn't offer centos7 but says to use Docker if you want other environments.

Using the `centos:7.9.2009` docker image you can `yum install python3` and get python 3.6.8.

As long as all our dependencies are happy with python 3.6 that should be fine.

**Comment by kaushik-work** [comment]
I was thinking of building w. Py3.9 for the next release because of #109 (which can probably be fixed in Python for older versions).

So the hypothesis is that with `centos:7.9.2009` the binary distribution would be compatible with most linux distros?

I do tend to think that linux users will be more likely to be able to `pip install` or `pipx install` things also ...

**Comment by mr-c** [comment]
Time to make some manylinux binary wheels!

**Comment by tetron** [comment]
That's the official-ish Python way?  Let's try it.

**Comment by tetron** [comment]
@kaushik-work for this use case I'm targeting here which is someone using vscode to edit CWL on a remote (linux) host, having benten install seamlessly is still a key part of the experience.

**Comment by tetron** [comment]
@mr-c we arn't building binary wheels, we're building standalone executables with pyinstaller.

Unfortunately, manylinux considers this to be out of scope: https://github.com/pypa/manylinux/issues/255

The recommendation is to fork manylinux and reenable building with shared libraries, so I'm trying that.

**Comment by tetron** [comment]
See #111

**Comment by tetron** [comment]
(Confirmed that the 'manylinux' build works on Ubuntu 16.04).
