### ISSUE TITLE
documentation improvements:

### ISSUE THREAD

**Issue by hmenager** [rabix/benten#40]
The documentation is fine but could be improved:
- add a "quick setup" for various setups, like ubuntu+vscode (stub here: https://gist.github.com/hmenager/2c56c3fc6ab25c32ad03d4becdabd4bb)
- the "VI setup" page should be restructured in a more chronological "step-by-step" order.

**Comment by kaushik-work** [comment]
Thanks so much for testing it out and giving feedback @hmenager ! I've strated working on the docs. One interesting thing I found is that not only do you need vim8 if you use vim8.1 you start to get a lot more features out of the box:

<img width="840" alt="Screen Shot 2019-07-27 at 9 30 22 AM" src="https://user-images.githubusercontent.com/6299530/61991502-320c0980-b051-11e9-852a-c4f855a3fa22.png">
