### ISSUE TITLE
No stdout / stderr for CommandOutputParameter type

### ISSUE THREAD

**Issue by illusional** [rabix/benten#74]
Version: `2019.12.06`
IDE: `vscode` (Version: 1.41.0)

Benten is reporting a problem when `stderr` | `stdout` is used as a type on a CommandOutputParameter, but I believe (and CWLTool validate is saying) it's okay.

![image](https://user-images.githubusercontent.com/22381693/71047143-c86ed200-218e-11ea-9df3-7390010143cd.png)

 

Minimum example:

```cwl
cwlVersion: v1.0
class: CommandLineTool
baseCommand: "echo"
inputs:
  inp:
    type: File
    inputBinding:
        position: 0
outputs:
  std: stdout
```

**Comment by kaushik-work** [comment]
@illusional Thanks for reporting this. 

Did you first install Benten before Sept 2019? If that is possible, could you try one check - under `~/.config/sevenbridges/benten/` can you remove the `schema-v1.0.json` file? In the original schema these were not formally written up as acceptable types. I patched the schema that is distributed with Benten, but only on 13th Sept (https://github.com/rabix/benten/blob/84868af60a6a997bb49887efdabe77bb392d5135/benten/000.package.data/schema-v1.0.json#L237). If you installed it earlier the new schema will not overwrite the existing one. Deleting and restarting Benten will copy over the news schema.

If this is not the issue, I will look into it. Thanks!

**Comment by illusional** [comment]
That was it, thanks @kaushik-work!

**Comment by GravityCore** [comment]
I seem to experience a similar problem with VSCode 1.107.1 extension version `2021.1.25` installed roughly a month ago, but now with specifying cwlVersion: v1.2 instead (v1.0 and v1.1 seem fine):
```cwl
cwlVersion: v1.2
class: CommandLineTool
baseCommand: "echo"
inputs:
  inp:
    type: File
    inputBinding:
        position: 0
outputs:
  std: stdout
```
