### ISSUE TITLE
Installing Rabix Benten using pipx 0.15.0.0+ doesn't work

### ISSUE THREAD

**Issue by vemonet** [rabix/benten#85]
Trying to reinstall Rabix Benten following the GitHub README:

```
pipx install --spec git+https://github.com/rabix/benten.git benten
```

But according to [pipx 0.15.0.0 changelog](https://pipxproject.github.io/pipx/changelog/), pipx doesn't support the `--spec` flag anymore

> install now has no `--spec` option. You may specify any valid pip specification for install's main argument.

`pipx` documentation is quite vague about what needs to be done

I tried the following, but none are working:
```
pipx install benten
pipx install benten git+https://github.com/rabix/benten.git
pipx install git+https://github.com/rabix/benten.git
```

Do you know how benten can be properly installed using pipx `0.15.0.0+` ?

Thanks a lot!

**Comment by kaushik-work** [comment]
Hello @vemonet , 

Thank you for pointing this out! I will revise the installation instructions. However, I'm surprised that your first and last command lines do not work. For me, with `pipx 0.15.1.3` they do.

```
(benten) KG-mac:~ kghose$ pipx --version
0.15.1.3
(benten) KG-mac:~ kghose$ pipx install benten
'benten' already seems to be installed. Not modifying existing installation in '/Users/kghose/.local/pipx/venvs/benten'. Pass '--force' to force installation.
(benten) KG-mac:~ kghose$ pipx install --force benten
Installing to existing directory '/Users/kghose/.local/pipx/venvs/benten'
  installed package benten 2020.2.6, Python 3.7.1
  These apps are now globally available
    - benten-ls
done! ✨ 🌟 ✨
```

This installs the latest version released on pypi.

```
(benten) KG-mac:~ kghose$ pipx install git+https://github.com/rabix/benten.git
'benten' already seems to be installed. Not modifying existing installation in '/Users/kghose/.local/pipx/venvs/benten'. Pass '--force' to force installation.
(benten) KG-mac:~ kghose$ pipx install git+https://github.com/rabix/benten.git --force
Installing to existing directory '/Users/kghose/.local/pipx/venvs/benten'
  installed package benten 2020.2.19, Python 3.7.1
  These apps are now globally available
    - benten-ls
done! ✨ 🌟 ✨
```
This installs the latest from `master` 

Which version of `pipx` are you using?

**Comment by vemonet** [comment]
Thanks for the quick and helpful reply!

I have pipx `0.15.1.3` installed

I was also surprised that `pipx install benten` would not work, but I found out why!

I was getting the following error:

```
ERROR: Could not find a version that satisfies the requirement benten (from versions: none)
ERROR: No matching distribution found for benten

Error installing benten.
```

Due to the fact `pipx` was installed using **Python 3.6** 

I needed to make sure `pipx` use 3.7 : 

```
pipx install benten --python python3.7
```

And got:

```
installed package benten 2020.2.6, Python 3.7.6
  These apps are now globally available
    - benten-ls
```

By the way, for a daily use would you recommend to install using the pip package or the GitHub repo?

Thanks a lot!

**Comment by kaushik-work** [comment]
Hi @vemonet thanks for finding this option! I will put that in the docs too.

If you are an experienced user, I think installing from github master is fine. I usually collect a bunch of fixes and new features before creating a release on pypi, so the release is a bit behind.
