### ISSUE TITLE
Indistinguishable text when previewing CWL under a dark color theme

### ISSUE THREAD

**Issue by nanxstats** [rabix/benten#91]
Node names are indistinguishable when previewing the CWL using a dark theme:

<img width="1661" alt="Screen Shot 2020-04-25 at 2 15 23 PM" src="https://user-images.githubusercontent.com/199363/80287395-65beb180-86ff-11ea-9bd3-378c9509b6d4.png">

To resolve this, might want to consider either force the preview panel to have a light background, like one would do in LaTeX previewers, or, determine the theme is light or dark and apply font colors accordingly (not sure if the current vscode API supports getting this though)

**Comment by kaushik-work** [comment]
Thanks for reporting this @nanxstats . I would imagine the best solution would be to detect the theme and supply two color sets depending on the theme. There are indications that this may be impossible: https://github.com/microsoft/vscode/issues/46940

The best short term solution might be to pin the preview background color.
