### ISSUE TITLE
Publish vscode extension in Open VSX registry

### ISSUE THREAD

**Issue by stain** [rabix/benten#94]
As the binaries of VSCode includes non-open-source components and Microsoft telemetry, alternative packaging like like [VSCodium](https://vscodium.com/) provide true open source binaries. Users may also have compiled VSCode locally, or use [code-in-browser](https://github.com/cdr/code-server). In any of these cases, the normal VSCode marketplace is not available, as it requires using the official binaries. See [this blog](https://www.gitpod.io/blog/open-vsx/) for details.

So this issue is to request if the benten vscode extension can also be published to the open repository https://open-vsx.org/ which is used by VSCodium and other packages of the open source vscode.

**Comment by kaushik-work** [comment]
Notes to self:

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

https://github.com/eclipse/openvsx/blob/master/cli/README.md

**Comment by kaushik-work** [comment]
https://open-vsx.org/extension/sbg-rabix/benten-cwl
